# Generated by Django 4.0 on 2021-12-15 16:13

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='path',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
