# Generated by Django 4.0 on 2021-12-24 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_alter_comment_id_alter_like_id_alter_picture_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post')},
        ),
        migrations.AlterIndexTogether(
            name='like',
            index_together={('user', 'post')},
        ),
    ]
