# Generated by Django 4.0 on 2021-12-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_alter_like_unique_together_alter_like_index_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
